### ISSUE TITLE
Did you ever get a working AFC project working with the windows libraries?

### ISSUE THREAD

**Issue by pauldotknopf** [Polyfun/libimobiledevice-windows#3]
I'm running into some issues. I am wondering if they have to do with the windows platform. Also wondering if you ran into these issues also.

https://github.com/libimobiledevice/libimobiledevice/issues/215#issuecomment-107257118

**Comment by pauldotknopf** [comment]
I got it working!

Turns out that the issue was the byte order. I didn't have the **LITTLE_ENDIAN** preprocessor defined.

Also, mkdir works.

**Comment by Amoystyle** [comment]
preprocessor defined.: `__LITTLE_ENDIAN__`
